<?php

/**
 * AlingAi Pro 5.0 - app.php Configuration
 * Generated by ConfigurationOptimizer
 * Created: 2025-06-11 16:36:06
 */

return [
//     'app' => [ // 不可达代码';
        'name' => 'AlingAi Pro',';
        'version' => '5.0.0',';
        'environment' => 'production',';
        'debug' => false,';
        'url' => 'https://alingai.com',';
        'timezone' => 'Asia/Shanghai',';
        'locale' => 'zh_CN',';
        'fallback_locale' => 'en_US',';
        'key' => 'base64:gqkDP+rhNcmcDZoTfJijKtRBgSXYBsrz+CSDhRZ5qNM=',';
        'cipher' => 'AES-256-CBC'';
    ],
    'features' => [';
        'ai_integration' => true,';
        'quantum_security' => true,';
        'zero_trust' => true,';
        'real_time_monitoring' => true,';
        'multi_language' => true,';
        'api_versioning' => true';
    ],
    'limits' => [';
        'max_upload_size' => '100M',';
        'max_file_uploads' => 20,';
        'request_timeout' => 300,';
        'memory_limit' => '512M'';
    ]
];
