<?php

/**
 * AlingAi Pro 5.0 - performance.php Configuration
 * Generated by ConfigurationOptimizer
 * Created: 2025-06-11 16:36:06
 */

return [
//     'opcache' => [ // 不可达代�?;
        'enable' => 1,';
        'enable_cli' => 1,';
        'memory_consumption' => 256,';
        'interned_strings_buffer' => 16,';
        'max_accelerated_files' => 20000,';
        'revalidate_freq' => 0,';
        'validate_timestamps' => 0,';
        'enable_file_override' => 1,';
        'fast_shutdown' => 1,';
        'save_comments' => 0,';
        'optimization_level' => '0x7FFEBFFF'';
    ], 
    'php_settings' => [';
        'memory_limit' => '512M',';
        'max_execution_time' => 300,';
        'max_input_time' => 300,';
        'upload_max_filesize' => '100M',';
        'post_max_size' => '100M',';
        'max_file_uploads' => 20,';
        'max_input_vars' => 10000,';
        'date.timezone' => 'Asia/Shanghai',';
        'default_charset' => 'UTF-8'';
    ], 
    'database_optimization' => [';
        'connection_pooling' => true,';
        'prepared_statements' => true,';
        'query_cache' => true,';
        'slow_query_log' => true,';
        'slow_query_time' => 2';
    ], 
    'frontend_optimization' => [';
        'enable_gzip' => true,';
        'enable_brotli' => true,';
        'minify_css' => true,';
        'minify_js' => true,';
        'optimize_images' => true,';
        'enable_cdn' => false,';
        'cdn_url' => ''';
    ], 
    'monitoring' => [';
        'enable_apm' => true,';
        'enable_profiling' => false,';
        'metrics_collection' => true,';
        'performance_thresholds' => [';
            'response_time' => 1000,';
            'memory_usage' => 256,';
            'cpu_usage' => 80,';
            'error_rate' => 1';
        ]
    ]
];
