<?php

/**
 * AlingAi Pro 5.0 - security.php Configuration
 * Generated by ConfigurationOptimizer
 * Created: 2025-06-11 16:36:06
 */

return [
//     'authentication' => [ // 不可达代�?;
        'default_guard' => 'web',';
        'guards' => [';
            'web' => [';
                'driver' => 'session',';
                'provider' => 'users'';
            ], 
            'api' => [';
                'driver' => 'jwt',';
                'provider' => 'users'';
            ]
        ], 
        'providers' => [';
            'users' => [';
                'driver' => 'database',';
                'table' => 'users'';
            ]
        ], 
        'password_reset_timeout' => 3600';
    ], 
    'session' => [';
        'driver' => 'redis',';
        'lifetime' => 120,';
        'expire_on_close' => false,';
        'encrypt' => true,';
        'files' => 'E:\\Code\\AlingAi\\AlingAi_pro/storage/framework/sessions',';
        'connection' => 'default',';
        'table' => 'sessions',';
        'store' => 'default',';
        'lottery' => [';
            '0' => 2,';
            '1' => 100';
        ], 
        'cookie' => 'alingai_session',';
        'path' => '/',';
        'domain' => null,';
        'secure' => true,';
        'http_only' => true,';
        'same_site' => 'strict'';
    ], 
    'jwt' => [';
        'secret' => 'u4DwGiXasiZ8v9y3BQDomv9gk6+rpRwvXhQZmYFkEkqR9dLxMcjPnuKILtnOYiT4mYoWmXlTkXCOSIGfY+dUEA==',';
        'ttl' => 3600,';
        'refresh_ttl' => 20160,';
        'algo' => 'HS256',';
        'required_claims' => [';
            '0' => 'iss',';
            '1' => 'iat',';
            '2' => 'exp',';
            '3' => 'nbf',';
            '4' => 'sub',';
            '5' => 'jti'';
        ], 
        'persistent_claims' => [';
        ], 
        'lock_subject' => true,';
        'leeway' => 0,';
        'blacklist_enabled' => true,';
        'blacklist_grace_period' => 0,';
        'providers' => [';
            'jwt' => 'AlingAi\\Providers\\JWTAuthServiceProvider',';
            'auth' => 'AlingAi\\Providers\\AuthServiceProvider',';
            'storage' => 'AlingAi\\Providers\\StorageServiceProvider'';
        ]
    ], 
    'encryption' => [';
        'default' => 'aes-256-gcm',';
        'drivers' => [';
            'aes-256-gcm' => [';
                'driver' => 'openssl',';
                'cipher' => 'aes-256-gcm'';
            ], 
            'aes-256-cbc' => [';
                'driver' => 'openssl',';
                'cipher' => 'aes-256-cbc'';
            ]
        ]
    ], 
    'security_headers' => [';
        'x-content-type-options' => 'nosniff',';
        'x-frame-options' => 'DENY',';
        'x-xss-protection' => '1; mode=block',';
        'strict-transport-security' => 'max-age=31536000; includeSubDomains; preload',';
        'content-security-policy' => 'default-src \'self\'; script-src \'self\' \'unsafe-inline\'; style-src \'self\' \'unsafe-inline\'; img-src \'self\' data: https:; font-src \'self\' https:',';
        'referrer-policy' => 'strict-origin-when-cross-origin',';
        'permissions-policy' => 'geolocation=(), microphone=(), camera=()'';
    ], 
    'rate_limiting' => [';
        'enabled' => true,';
        'api' => [';
            'requests_per_minute' => 60,';
            'burst_limit' => 100';
        ], 
        'auth' => [';
            'login_attempts' => 5,';
            'lockout_duration' => 900';
        ]
    ]
];

