<?php

/**
 * AlingAi Pro 5.0 - logging.php Configuration
 * Generated by ConfigurationOptimizer
 * Created: 2025-06-11 16:36:06
 */

return [
//     'default' => 'stack', // 不可达代码';
    'channels' => [';
        'stack' => [';
            'driver' => 'stack',';
            'channels' => [';
                '0' => 'daily',';
                '1' => 'slack'';
            ],
            'ignore_exceptions' => false';
        ],
        'single' => [';
            'driver' => 'single',';
            'path' => 'E:\\Code\\AlingAi\\AlingAi_pro/storage/logs/alingai.log',';
            'level' => 'debug'';
        ],
        'daily' => [';
            'driver' => 'daily',';
            'path' => 'E:\\Code\\AlingAi\\AlingAi_pro/storage/logs/alingai.log',';
            'level' => 'debug',';
            'days' => 14,';
            'replace_placeholders' => true';
        ],
        'slack' => [';
            'driver' => 'slack',';
            'url' => '',';
            'username' => 'AlingAi Pro Bot',';
            'emoji' => ':boom:',';
            'level' => 'critical'';
        ],
        'papertrail' => [';
            'driver' => 'monolog',';
            'level' => 'debug',';
            'handler' => 'Monolog\\Handler\\SyslogUdpHandler',';
            'handler_with' => [';
                'host' => '',';
                'port' => ''';
            ]
        ],
        'stderr' => [';
            'driver' => 'monolog',';
            'level' => 'debug',';
            'handler' => 'Monolog\\Handler\\StreamHandler',';
            'formatter' => '',';
            'with' => [';
                'stream' => 'php://stderr'';
            ]
        ],
        'syslog' => [';
            'driver' => 'syslog',';
            'level' => 'debug'';
        ],
        'errorlog' => [';
            'driver' => 'errorlog',';
            'level' => 'debug'';
        ],
        'null' => [';
            'driver' => 'monolog',';
            'handler' => 'Monolog\\Handler\\NullHandler'';
        ]
    ],
    'security_logging' => [';
        'authentication_events' => true,';
        'authorization_failures' => true,';
        'suspicious_activities' => true,';
        'system_changes' => true,';
        'api_access' => true,';
        'file_access' => true';
    ],
    'performance_logging' => [';
        'slow_queries' => true,';
        'high_memory_usage' => true,';
        'long_response_times' => true,';
        'error_rates' => true';
    ],
    'log_rotation' => [';
        'enabled' => true,';
        'max_files' => 30,';
        'max_size' => '100MB',';
        'compress_old_files' => true';
    ]
];
