<?php

/**
 * AlingAi Pro 5.0 - security.php Configuration
 * Generated by ConfigurationOptimizer
 * Created: 2025-06-11 16:36:06
 */

return [
    /*
    |--------------------------------------------------------------------------
    | 身份验证
    |--------------------------------------------------------------------------
    */
    'auth' => [
        // 密码哈希选项
        'password_hash' => [
            'algorithm' => PASSWORD_BCRYPT,
            'options' => [
                'cost' => 12, // 哈希计算复杂度，越高越安全但性能消耗越大
            ],
        ],
        
        // 令牌设置
        'tokens' => [
            'lifetime' => 3600, // 令牌有效期（秒）
            'refresh_lifetime' => 86400, // 刷新令牌有效期（秒）
            'algorithm' => 'HS256', // JWT签名算法
        ],
        
        // 登录尝试限制
        'throttle' => [
            'enabled' => true,
            'max_attempts' => 5, // 最大尝试次数
            'decay_minutes' => 10, // 锁定时间（分钟）
        ],
        
        // 认证配置
        'enable_2fa' => (bool)($_ENV['ENABLE_2FA'] ?? false),
        'session_lifetime' => (int)($_ENV['SESSION_LIFETIME'] ?? 3600), // 默认1小时
        'max_login_attempts' => (int)($_ENV['MAX_LOGIN_ATTEMPTS'] ?? 5),
        'lockout_time' => (int)($_ENV['LOCKOUT_TIME'] ?? 900), // 默认15分钟
        'remember_me_lifetime' => (int)($_ENV['REMEMBER_ME_LIFETIME'] ?? 2592000), // 默认30天
        'secure_cookies' => (bool)($_ENV['SECURE_COOKIES'] ?? true),
        'api_rate_limit' => (int)($_ENV['API_RATE_LIMIT'] ?? 60), // 每分钟请求数
    ],
    
    /*
    |--------------------------------------------------------------------------
    | 会话安全
    |--------------------------------------------------------------------------
    */
    'session' => [
        'secure' => true, // 仅通过HTTPS发送cookie
        'http_only' => true, // 禁止JavaScript访问cookie
        'same_site' => 'lax', // Cookie SameSite策略
        'lifetime' => 120, // 会话生命周期（分钟）
        'regenerate' => true, // 定期重新生成会话ID
    ],
    
    /*
    |--------------------------------------------------------------------------
    | CORS设置
    |--------------------------------------------------------------------------
    */
    'cors' => [
        'allowed_origins' => explode(',', $_ENV['CORS_ALLOWED_ORIGINS'] ?? '*'),
        'allowed_methods' => explode(',', $_ENV['CORS_ALLOWED_METHODS'] ?? 'GET,POST,PUT,DELETE,OPTIONS'),
        'allowed_headers' => explode(',', $_ENV['CORS_ALLOWED_HEADERS'] ?? 'Content-Type,Authorization,X-Requested-With'),
        'exposed_headers' => explode(',', $_ENV['CORS_EXPOSED_HEADERS'] ?? ''),
        'max_age' => (int)($_ENV['CORS_MAX_AGE'] ?? 3600),
        'supports_credentials' => (bool)($_ENV['CORS_SUPPORTS_CREDENTIALS'] ?? false),
    ],
    
    /*
    |--------------------------------------------------------------------------
    | 内容安全策略
    |--------------------------------------------------------------------------
    */
    'csp' => [
        'enabled' => (bool)($_ENV['CSP_ENABLED'] ?? true),
        'report_only' => (bool)($_ENV['CSP_REPORT_ONLY'] ?? false),
        'report_uri' => $_ENV['CSP_REPORT_URI'] ?? '/api/v1/security/csp-report',
    ],
    
    /*
    |--------------------------------------------------------------------------
    | XSS防护
    |--------------------------------------------------------------------------
    */
    'xss' => [
        'enabled' => true,
        'mode' => 'block', // 'block' 或 'filter'
    ],
    
    /*
    |--------------------------------------------------------------------------
    | CSRF防护
    |--------------------------------------------------------------------------
    */
    'csrf' => [
        'enabled' => true,
        'exclude_routes' => [
            'api/public/*', // 排除公开API
        ],
    ],
    
    /*
    |--------------------------------------------------------------------------
    | 文件上传安全
    |--------------------------------------------------------------------------
    */
    'uploads' => [
        'max_size' => 10485760, // 最大上传大小（字节）
        'allowed_types' => [
            'image/jpeg',
            'image/png',
            'image/gif',
            'application/pdf',
            'application/msword',
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            'text/plain',
        ],
        'disallowed_extensions' => [
            'php', 'phtml', 'php3', 'php4', 'php5', 'php7', 'pht', 'phar', 'exe', 'sh', 'bat', 'cmd',
        ],
        'scan_files' => true, // 扫描上传文件是否包含恶意代码
    ],
    
    /*
    |--------------------------------------------------------------------------
    | 日志记录
    |--------------------------------------------------------------------------
    */
    'logging' => [
        'security_events' => true, // 记录安全相关事件
        'login_attempts' => true, // 记录登录尝试
        'admin_actions' => true, // 记录管理员操作
    ],
    
    // 加密配置
    'encryption' => [
        'enable_quantum_encryption' => (bool)($_ENV['ENABLE_QUANTUM_ENCRYPTION'] ?? false),
        'default_algorithm' => $_ENV['DEFAULT_ENCRYPTION_ALGORITHM'] ?? 'AES-256-GCM',
        'key_rotation_interval' => (int)($_ENV['KEY_ROTATION_INTERVAL'] ?? 86400), // 默认24小时
        'api_encryption' => (bool)($_ENV['API_ENCRYPTION_ENABLED'] ?? true),
        'api_encryption_algorithm' => $_ENV['API_ENCRYPTION_ALGORITHM'] ?? 'AES-256-CBC',
        'data_encryption' => (bool)($_ENV['DATA_ENCRYPTION_ENABLED'] ?? true),
        'hash_algorithm' => $_ENV['HASH_ALGORITHM'] ?? 'sha256',
    ],
    
    // JWT配置
    'jwt' => [
        'secret' => $_ENV['JWT_SECRET'] ?? '',
        'algorithm' => $_ENV['JWT_ALGORITHM'] ?? 'HS256',
        'expires_in' => (int)($_ENV['JWT_EXPIRES_IN'] ?? 3600), // 默认1小时
        'refresh_expires_in' => (int)($_ENV['JWT_REFRESH_EXPIRES_IN'] ?? 604800), // 默认7天
    ],
    
    // 中间件配置
    'middleware' => [
        'api_encryption' => [
            'enabled' => (bool)($_ENV['API_ENCRYPTION_ENABLED'] ?? true),
            'excluded_paths' => explode(',', $_ENV['API_ENCRYPTION_EXCLUDED_PATHS'] ?? '/api/v1/system/info,/api/health'),
            'algorithm' => $_ENV['API_ENCRYPTION_ALGORITHM'] ?? 'AES-256-CBC',
            'debug_mode' => (bool)($_ENV['API_ENCRYPTION_DEBUG'] ?? false),
        ],
        'authentication' => [
            'public_paths' => explode(',', $_ENV['AUTH_PUBLIC_PATHS'] ?? '/api/v1/system/info,/api/health,/api/auth/login,/api/auth/register'),
            'token_header' => $_ENV['AUTH_TOKEN_HEADER'] ?? 'Authorization',
            'token_prefix' => $_ENV['AUTH_TOKEN_PREFIX'] ?? 'Bearer',
            'session_header' => $_ENV['AUTH_SESSION_HEADER'] ?? 'X-Session-ID',
        ],
    ],
    
    // 密码策略
    'password_policy' => [
        'min_length' => (int)($_ENV['PASSWORD_MIN_LENGTH'] ?? 8),
        'require_uppercase' => (bool)($_ENV['PASSWORD_REQUIRE_UPPERCASE'] ?? true),
        'require_lowercase' => (bool)($_ENV['PASSWORD_REQUIRE_LOWERCASE'] ?? true),
        'require_number' => (bool)($_ENV['PASSWORD_REQUIRE_NUMBER'] ?? true),
        'require_special' => (bool)($_ENV['PASSWORD_REQUIRE_SPECIAL'] ?? false),
        'expiry_days' => (int)($_ENV['PASSWORD_EXPIRY_DAYS'] ?? 90),
    ],
];
